# Generated by Django 4.0 on 2022-01-08 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerType',
            fields=[
                ('defaultobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultobject')),
            ],
            options={
                'verbose_name': 'containertype',
                'verbose_name_plural': 'containertypes',
            },
            bases=('core.defaultobject', models.Model),
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('defaultobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultobject')),
                ('container_type_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_equipment.containertype', verbose_name='')),
            ],
            options={
                'verbose_name': 'container',
                'verbose_name_plural': 'containers',
            },
            bases=('core.defaultobject', models.Model),
        ),
    ]
