# Generated by Django 4.0 on 2022-01-08 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_type_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_equipment.containertype', verbose_name='container_type'),
        ),
    ]
