# Generated by Django 4.0 on 2022-01-08 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('room_equipment', '0002_alter_container_container_type_fk'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerLevel',
            fields=[
                ('defaultobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultobject')),
                ('container_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_equipment.container', verbose_name='container')),
            ],
            options={
                'verbose_name': 'containerlevel',
                'verbose_name_plural': 'containerlevels',
            },
            bases=('core.defaultobject', models.Model),
        ),
    ]
