# Generated by Django 4.0 on 2022-01-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_equipment', '0003_containerlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'LocationType',
                'verbose_name_plural': 'LocationTypes',
            },
        ),
        migrations.AlterModelOptions(
            name='container',
            options={'verbose_name': 'Container', 'verbose_name_plural': 'Containers'},
        ),
        migrations.AlterModelOptions(
            name='containerlevel',
            options={'verbose_name': 'Containerlevel', 'verbose_name_plural': 'Containerlevels'},
        ),
        migrations.AlterModelOptions(
            name='containertype',
            options={'verbose_name': 'Containertype', 'verbose_name_plural': 'Containertypes'},
        ),
    ]
