# Generated by Django 4.0 on 2022-01-08 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_equipment', '0005_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='LocationType',
        ),
    ]
