# Generated by Django 4.0 on 2022-01-08 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('room_equipment', '0006_delete_location_delete_locationtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationType',
            fields=[
                ('defaultobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultobject')),
            ],
            options={
                'verbose_name': 'LocationType',
                'verbose_name_plural': 'LocationTypes',
            },
            bases=('core.defaultobject', models.Model),
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('defaultobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.defaultobject')),
                ('container_level_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_equipment.container', verbose_name='container_level')),
                ('location_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_equipment.locationtype', verbose_name='location_type')),
            ],
            options={
                'verbose_name': 'location',
                'verbose_name_plural': 'locations',
            },
            bases=('core.defaultobject', models.Model),
        ),
    ]
