# Generated by Django 4.0 on 2022-01-08 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_equipment', '0007_locationtype_location'),
        ('map', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='container_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='room_equipment.container', verbose_name='container'),
        ),
    ]
